import os

TWITTER_CONSUMER_KEY = os.environ("TWITTER_CONSUMER_KEY")
TWITTER_CONSUMER_SECRET = os.environ("TWITTER_CONSUMER_SECRET")
TWITTER_ACCESS_TOKEN = os.environ("TWITTER_ACCESS_TOKEN")
TWITTER_ACCESS_SECRET = os.environ("TWITTER_ACCESS_SECRET")
LIVESPLIT_HOST = os.environ("TWITTER_ACCESS_SECRET", "localhost")
LIVESPLIT_PORT = int(os.environ("TWITTER_ACCESS_SECRET", "16834"))
